#!/usr/local/bin/node

let fs = require("fs");
let Phrase = require("sahvith-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line) {
    let phrase = new Phrase(line);
    if (phrase.palindrome()) {
        fs.writeFile("./palindromes.txt", line + "\n", function(error) {
            if (error)
                return console.log(error);
        });
        console.log("palindrome detected:", line);
    }
});